### ISSUE TITLE
Account expiration should not apply to global users.

### ISSUE THREAD

**Issue by garnertb** [StatEngine/stat-engine#213] opened 2019-03-21 19:59 UTC
Global users are able to switch into different departments.  If you switch into a department that an expired subscription, you are unable to switch to different department after.

@larskendall ping me if you need more details.

**Comment by larskendall** [comment] 2019-03-29 20:25
@garnertb How are global users differentiated within the database?

What exactly prevents global users from signing out at the moment? There should be a **Sign Out** button on the subscription expired dialog, so I'm curious if there's some edge case where global users are seeing something different.

**Comment by chopchop505** [comment] 2019-03-29 20:41
```
isGlobal() {
        return this.roles.indexOf('global') >= 0
               || this.roles.indexOf('admin') >= 0;
      },
```

**Comment by chopchop505** [comment] 2019-03-29 20:42
The problem exists with admin users to.  If you switch to an expired account, you cannot interact with the page to change your department because of the subscription modal

**Comment by chopchop505** [comment] 2019-03-29 20:43
We probably shouldn't show the subscription modal for global or admin users.

**Comment by larskendall** [comment] 2019-03-29 20:44
@chopchop505 Oh I understand now. The problem is they can't reassign to a different department. That makes sense. I guess we should just not show that subscription expired modal for global/admin users then?

**Comment by chopchop505** [comment] 2019-03-29 20:45
yup

**Closed** 2019-03-30 02:38 UTC
